/**
 * Client Repository
 *
 * CRUD operations for the clients table (connected devices).
 */

import type { Client, ClientType, Priority } from '@lecoder/shared';
import { type SqlClient, getClient } from '../client.js';

// ============================================================================
// Types
// ============================================================================

/**
 * Client creation data
 */
export interface CreateClientInput {
  id: string; // Client ID is provided (generated by WebSocket layer)
  sessionId: string;
  userId?: string;
  clientType: ClientType;
  priority?: Priority;
  userAgent?: string;
  ipAddress?: string;
}

/**
 * Client update data
 */
export interface UpdateClientInput {
  priority?: Priority;
  lastHeartbeatAt?: Date;
}

/**
 * Client query filters
 */
export interface ClientFilter {
  sessionId?: string;
  userId?: string;
  clientType?: ClientType;
  priority?: Priority;
}

/**
 * Database row type
 */
interface ClientRow {
  id: string;
  session_id: string;
  user_id: string | null;
  client_type: string;
  priority: string;
  user_agent: string | null;
  ip_address: string | null;
  connected_at: Date;
  last_heartbeat_at: Date;
}

// ============================================================================
// Mappers
// ============================================================================

/**
 * Map database row to Client type
 */
function mapRowToClient(row: ClientRow): Client {
  return {
    id: row.id,
    sessionId: row.session_id,
    userId: row.user_id ?? undefined,
    clientType: row.client_type as ClientType,
    priority: row.priority as Priority,
    userAgent: row.user_agent ?? undefined,
    ipAddress: row.ip_address ?? undefined,
    connectedAt: row.connected_at,
    lastHeartbeatAt: row.last_heartbeat_at,
  };
}

// ============================================================================
// Repository Functions
// ============================================================================

/**
 * Find client by ID
 */
export async function findById(id: string, sql?: SqlClient): Promise<Client | null> {
  const client = sql ?? getClient();

  const rows = await client<ClientRow[]>`
    SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
    FROM clients
    WHERE id = ${id}
  `;

  if (rows.length === 0) {
    return null;
  }

  return mapRowToClient(rows[0]);
}

/**
 * Create a new client
 */
export async function create(input: CreateClientInput, sql?: SqlClient): Promise<Client> {
  const dbClient = sql ?? getClient();

  const rows = await dbClient<ClientRow[]>`
    INSERT INTO clients (id, session_id, user_id, client_type, priority, user_agent, ip_address)
    VALUES (
      ${input.id},
      ${input.sessionId},
      ${input.userId ?? null},
      ${input.clientType},
      ${input.priority ?? 'normal'},
      ${input.userAgent ?? null},
      ${input.ipAddress ?? null}
    )
    RETURNING id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
  `;

  return mapRowToClient(rows[0]);
}

/**
 * Update client by ID
 */
export async function update(
  id: string,
  input: UpdateClientInput,
  sql?: SqlClient
): Promise<Client | null> {
  const dbClient = sql ?? getClient();

  const rows = await dbClient<ClientRow[]>`
    UPDATE clients
    SET
      priority = COALESCE(${input.priority ?? null}, priority),
      last_heartbeat_at = COALESCE(${input.lastHeartbeatAt ?? null}, last_heartbeat_at)
    WHERE id = ${id}
    RETURNING id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
  `;

  if (rows.length === 0) {
    return null;
  }

  return mapRowToClient(rows[0]);
}

/**
 * Update client priority
 */
export async function updatePriority(
  id: string,
  priority: Priority,
  sql?: SqlClient
): Promise<boolean> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    UPDATE clients
    SET priority = ${priority}
    WHERE id = ${id}
  `;

  return result.count > 0;
}

/**
 * Record heartbeat (update last_heartbeat_at)
 */
export async function heartbeat(id: string, sql?: SqlClient): Promise<boolean> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    UPDATE clients
    SET last_heartbeat_at = NOW()
    WHERE id = ${id}
  `;

  return result.count > 0;
}

/**
 * Delete client by ID
 */
export async function deleteById(id: string, sql?: SqlClient): Promise<boolean> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    DELETE FROM clients
    WHERE id = ${id}
  `;

  return result.count > 0;
}

/**
 * List clients with filters
 */
export async function list(filter: ClientFilter = {}, sql?: SqlClient): Promise<Client[]> {
  const dbClient = sql ?? getClient();

  let rows: ClientRow[];

  if (filter.sessionId && filter.clientType) {
    rows = await dbClient<ClientRow[]>`
      SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
      FROM clients
      WHERE session_id = ${filter.sessionId} AND client_type = ${filter.clientType}
      ORDER BY connected_at DESC
    `;
  } else if (filter.sessionId) {
    rows = await dbClient<ClientRow[]>`
      SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
      FROM clients
      WHERE session_id = ${filter.sessionId}
      ORDER BY connected_at DESC
    `;
  } else if (filter.userId) {
    rows = await dbClient<ClientRow[]>`
      SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
      FROM clients
      WHERE user_id = ${filter.userId}
      ORDER BY connected_at DESC
    `;
  } else {
    rows = await dbClient<ClientRow[]>`
      SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
      FROM clients
      ORDER BY connected_at DESC
    `;
  }

  return rows.map(mapRowToClient);
}

/**
 * Get all clients for a session
 */
export async function getBySession(sessionId: string, sql?: SqlClient): Promise<Client[]> {
  return list({ sessionId }, sql);
}

/**
 * Get PC clients for a session
 */
export async function getPCClients(sessionId: string, sql?: SqlClient): Promise<Client[]> {
  return list({ sessionId, clientType: 'pc' }, sql);
}

/**
 * Get mobile clients for a session
 */
export async function getMobileClients(sessionId: string, sql?: SqlClient): Promise<Client[]> {
  return list({ sessionId, clientType: 'mobile' }, sql);
}

/**
 * Check if session has any exclusive client
 */
export async function hasExclusiveClient(sessionId: string, sql?: SqlClient): Promise<Client | null> {
  const dbClient = sql ?? getClient();

  const rows = await dbClient<ClientRow[]>`
    SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
    FROM clients
    WHERE session_id = ${sessionId} AND priority = 'exclusive'
    LIMIT 1
  `;

  if (rows.length === 0) {
    return null;
  }

  return mapRowToClient(rows[0]);
}

/**
 * Release exclusive control (reset to normal priority)
 */
export async function releaseExclusive(id: string, sql?: SqlClient): Promise<boolean> {
  return updatePriority(id, 'normal', sql);
}

/**
 * Release all exclusive clients for a session
 */
export async function releaseAllExclusive(sessionId: string, sql?: SqlClient): Promise<number> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    UPDATE clients
    SET priority = 'normal'
    WHERE session_id = ${sessionId} AND priority = 'exclusive'
  `;

  return result.count;
}

/**
 * Count clients for a session
 */
export async function countBySession(sessionId: string, sql?: SqlClient): Promise<number> {
  const dbClient = sql ?? getClient();

  const result = await dbClient<[{ count: string }]>`
    SELECT COUNT(*) as count FROM clients
    WHERE session_id = ${sessionId}
  `;

  return Number.parseInt(result[0].count, 10);
}

/**
 * Delete all clients for a session
 */
export async function deleteBySession(sessionId: string, sql?: SqlClient): Promise<number> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    DELETE FROM clients
    WHERE session_id = ${sessionId}
  `;

  return result.count;
}

/**
 * Find stale clients (no heartbeat for threshold duration)
 */
export async function findStale(
  thresholdSeconds: number,
  sql?: SqlClient
): Promise<Client[]> {
  const dbClient = sql ?? getClient();

  const rows = await dbClient<ClientRow[]>`
    SELECT id, session_id, user_id, client_type, priority, user_agent, ip_address, connected_at, last_heartbeat_at
    FROM clients
    WHERE last_heartbeat_at < NOW() - INTERVAL '1 second' * ${thresholdSeconds}
  `;

  return rows.map(mapRowToClient);
}

/**
 * Delete stale clients (no heartbeat for threshold duration)
 */
export async function deleteStale(thresholdSeconds: number, sql?: SqlClient): Promise<number> {
  const dbClient = sql ?? getClient();

  const result = await dbClient`
    DELETE FROM clients
    WHERE last_heartbeat_at < NOW() - INTERVAL '1 second' * ${thresholdSeconds}
  `;

  return result.count;
}

// ============================================================================
// Export
// ============================================================================

export const clientRepository = {
  findById,
  create,
  update,
  updatePriority,
  heartbeat,
  deleteById,
  list,
  getBySession,
  getPCClients,
  getMobileClients,
  hasExclusiveClient,
  releaseExclusive,
  releaseAllExclusive,
  countBySession,
  deleteBySession,
  findStale,
  deleteStale,
};

export default clientRepository;
