/**
 * HubClient
 *
 * Optional registration layer that turns a local `lecoder` daemon into a
 * runtime that a remote LeSearch Hub (`@lecoder/server`) can route work to.
 *
 * Activation:
 *   Set LECODER_HUB_URL (e.g. `https://hub.example.com`) and the daemon will:
 *     1. Register itself once on startup, getting back a runtime ID.
 *     2. Send a heartbeat every HEARTBEAT_MS milliseconds.
 *     3. Poll for tasks every POLL_MS milliseconds (consumed in M2).
 *
 * When LECODER_HUB_URL is not set, the daemon stays in single-machine mode
 * exactly as before — HubClient is a no-op.
 *
 * Auth:
 *   The hub token (LECODER_HUB_TOKEN) is sent as a Bearer header. The token
 *   is per-user and is generated by the hub when the user installs the CLI.
 *   We deliberately do NOT introduce a new auth provider here; the hub reuses
 *   the existing JWT/session-token plumbing.
 */

import { hostname, platform, arch, userInfo } from 'node:os';
import { VERSION } from '../version.js';

export const DEFAULT_HEARTBEAT_MS = 15_000;
export const DEFAULT_POLL_MS = 3_000;

export interface HubClientConfig {
  /** Hub base URL, e.g. `https://hub.example.com`. */
  hubUrl: string;
  /** Bearer token for hub auth. */
  hubToken?: string;
  /** Friendly name for this runtime (defaults to hostname). */
  runtimeName?: string;
  /** Heartbeat interval in ms. Set to 0 to disable. */
  heartbeatMs?: number;
  /** Poll interval in ms. Set to 0 to disable polling. */
  pollMs?: number;
  /** Logger. Falls back to console. */
  logger?: HubLogger;
  /** fetch implementation override (for tests). */
  fetchImpl?: typeof fetch;
}

export interface HubLogger {
  debug: (msg: string, meta?: Record<string, unknown>) => void;
  info: (msg: string, meta?: Record<string, unknown>) => void;
  warn: (msg: string, meta?: Record<string, unknown>) => void;
  error: (msg: string, meta?: Record<string, unknown>) => void;
}

const consoleLogger: HubLogger = {
  debug: (msg, meta) => console.debug(`[hub] ${msg}`, meta ?? ''),
  info: (msg, meta) => console.log(`[hub] ${msg}`, meta ?? ''),
  warn: (msg, meta) => console.warn(`[hub] ${msg}`, meta ?? ''),
  error: (msg, meta) => console.error(`[hub] ${msg}`, meta ?? ''),
};

export interface RuntimeRegistration {
  runtimeId: string;
  name: string;
  hostname: string;
  platform: string;
  arch: string;
  user: string;
  version: string;
}

export interface HubTask {
  id: string;
  title: string;
  body?: string;
  provider?: string;
  workingDirectory?: string;
}

export type HubClientStatus = 'idle' | 'connecting' | 'registered' | 'error';

/**
 * Build the registration payload describing this runtime.
 */
export function buildRegistration(config: Pick<HubClientConfig, 'runtimeName'>): Omit<RuntimeRegistration, 'runtimeId'> {
  const host = hostname();
  return {
    name: config.runtimeName?.trim() || host,
    hostname: host,
    platform: platform(),
    arch: arch(),
    user: safeUser(),
    version: VERSION,
  };
}

function safeUser(): string {
  try {
    return userInfo().username;
  } catch {
    return process.env.USER || process.env.USERNAME || 'unknown';
  }
}

/**
 * HubClient orchestrates registration, heartbeat, and task polling.
 *
 * It owns NO PTY state — when a task arrives the client emits an event and
 * leaves spawning to the daemon's existing AgentManager.
 */
export class HubClient {
  private readonly config: Required<Omit<HubClientConfig, 'logger' | 'fetchImpl' | 'runtimeName' | 'hubToken'>> & {
    runtimeName?: string;
    hubToken?: string;
  };
  private readonly logger: HubLogger;
  private readonly fetchImpl: typeof fetch;

  private status: HubClientStatus = 'idle';
  private runtimeId: string | null = null;
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  private pollTimer: ReturnType<typeof setInterval> | null = null;
  private taskHandlers: Array<(task: HubTask) => void> = [];

  constructor(config: HubClientConfig) {
    if (!config.hubUrl) {
      throw new Error('HubClient requires hubUrl');
    }

    this.config = {
      hubUrl: stripTrailingSlash(config.hubUrl),
      hubToken: config.hubToken,
      runtimeName: config.runtimeName,
      heartbeatMs: config.heartbeatMs ?? DEFAULT_HEARTBEAT_MS,
      pollMs: config.pollMs ?? DEFAULT_POLL_MS,
    };
    this.logger = config.logger ?? consoleLogger;
    this.fetchImpl = config.fetchImpl ?? globalThis.fetch.bind(globalThis);
  }

  /**
   * Register this daemon as a runtime with the hub and start heartbeat/poll
   * loops. Safe to call multiple times — repeated calls are no-ops once
   * registered.
   */
  async start(): Promise<RuntimeRegistration> {
    if (this.runtimeId) {
      return this.snapshot();
    }
    this.status = 'connecting';

    const registration = buildRegistration({ runtimeName: this.config.runtimeName });
    this.logger.info(`Registering runtime ${registration.name} with ${this.config.hubUrl}`);

    let response: Response;
    try {
      response = await this.fetchImpl(`${this.config.hubUrl}/fleet/register`, {
        method: 'POST',
        headers: this.headers(),
        body: JSON.stringify(registration),
      });
    } catch (err) {
      this.status = 'error';
      throw new Error(
        `Failed to reach hub at ${this.config.hubUrl}: ${err instanceof Error ? err.message : 'unknown error'}`
      );
    }

    if (!response.ok) {
      this.status = 'error';
      const body = await safeText(response);
      throw new Error(`Hub register failed (${response.status}): ${body}`);
    }

    const data = (await response.json()) as { runtimeId?: string };
    if (!data.runtimeId) {
      this.status = 'error';
      throw new Error('Hub register response missing runtimeId');
    }

    this.runtimeId = data.runtimeId;
    this.status = 'registered';
    this.logger.info(`Runtime registered`, { runtimeId: this.runtimeId });

    if (this.config.heartbeatMs > 0) {
      this.heartbeatTimer = setInterval(() => {
        this.heartbeat().catch((err) => {
          this.logger.warn(`Heartbeat failed: ${err instanceof Error ? err.message : 'unknown'}`);
        });
      }, this.config.heartbeatMs);
      this.heartbeatTimer.unref?.();
    }

    if (this.config.pollMs > 0) {
      this.pollTimer = setInterval(() => {
        this.pollTasks().catch((err) => {
          this.logger.warn(`Task poll failed: ${err instanceof Error ? err.message : 'unknown'}`);
        });
      }, this.config.pollMs);
      this.pollTimer.unref?.();
    }

    return this.snapshot();
  }

  /**
   * Stop heartbeat/poll loops. Does not deregister with the hub — the hub will
   * mark this runtime offline once heartbeats stop arriving.
   */
  async stop(): Promise<void> {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
    this.status = 'idle';
    this.runtimeId = null;
  }

  /** Register a handler invoked for each new task delivered by the hub. */
  onTask(handler: (task: HubTask) => void): void {
    this.taskHandlers.push(handler);
  }

  getStatus(): HubClientStatus {
    return this.status;
  }

  getRuntimeId(): string | null {
    return this.runtimeId;
  }

  /** Manually trigger a heartbeat (test hook). */
  async heartbeat(): Promise<void> {
    if (!this.runtimeId) return;
    const response = await this.fetchImpl(
      `${this.config.hubUrl}/fleet/${this.runtimeId}/heartbeat`,
      {
        method: 'POST',
        headers: this.headers(),
        body: JSON.stringify({ ts: Date.now() }),
      }
    );

    if (response.status === 404) {
      this.logger.warn('Hub forgot us, re-registering');
      this.runtimeId = null;
      await this.start();
      return;
    }
    if (!response.ok) {
      throw new Error(`heartbeat failed: ${response.status}`);
    }
  }

  /** Manually trigger a task poll (test hook). */
  async pollTasks(): Promise<HubTask[]> {
    if (!this.runtimeId) return [];

    const response = await this.fetchImpl(
      `${this.config.hubUrl}/fleet/${this.runtimeId}/tasks/next`,
      { method: 'GET', headers: this.headers() }
    );

    if (response.status === 204) return [];
    if (!response.ok) throw new Error(`poll failed: ${response.status}`);

    const body = (await response.json()) as { tasks?: HubTask[] };
    const tasks = body.tasks ?? [];
    for (const task of tasks) {
      for (const handler of this.taskHandlers) {
        try {
          handler(task);
        } catch (err) {
          this.logger.error(`Task handler threw`, {
            taskId: task.id,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
    }
    return tasks;
  }

  private snapshot(): RuntimeRegistration {
    const reg = buildRegistration({ runtimeName: this.config.runtimeName });
    return {
      runtimeId: this.runtimeId ?? '',
      ...reg,
    };
  }

  private headers(): Record<string, string> {
    const h: Record<string, string> = {
      'Content-Type': 'application/json',
      'User-Agent': `lecoder-mconnect/${VERSION}`,
    };
    if (this.config.hubToken) {
      h.Authorization = `Bearer ${this.config.hubToken}`;
    }
    return h;
  }
}

function stripTrailingSlash(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

async function safeText(response: Response): Promise<string> {
  try {
    return await response.text();
  } catch {
    return '<no body>';
  }
}

/**
 * Build a HubClient from the standard environment variables.
 * Returns null if LECODER_HUB_URL is not set.
 */
export function hubClientFromEnv(logger?: HubLogger): HubClient | null {
  const hubUrl = process.env.LECODER_HUB_URL;
  if (!hubUrl) return null;

  return new HubClient({
    hubUrl,
    hubToken: process.env.LECODER_HUB_TOKEN,
    runtimeName: process.env.LECODER_RUNTIME_NAME,
    logger,
  });
}
